### PR TITLE
Merge k6n10f RAM and DSP parameters into MODE_BITS

### PR DESCRIPTION
**Pull request by mkurc-ant**
This PR aggregates all parameters of DSPs and BRAMs into a single parameter named `MODE_BITS`.

### CODE REVIEW

**Comment by mkurc-ant** [comment]
@lpawelcz @tpagarani @rakeshm75 Please take a look.

**Review by tpagarani — APPROVED** [review]
lgtm

**Comment by lpawelcz** [comment]
If internal modules like `TDP18K_FIFO` or `fifo36_ctl` shouldn't be affected by those changes then everything looks good to me

**Comment by mkurc-ant** [comment]
Ok, merging.

**Pull request merged**
