### PR TITLE
Update k6n10f DSP simulation models

### PR DESCRIPTION
**Pull request by mkurc-ant**
This PR updates the simulation models plus fixes a bug around signed multiplication (test added).

### CODE REVIEW

**Comment by mkurc-ant** [comment]
@tpagarani @rakeshm75 Please take a look.

**Comment by rakeshm75** [comment]
I have reviewed the changes and it looks fine. Its good to merge. Only in the cells_sim.v file, in modules dsp_t1_20x18x64 & dsp_t1_10x9x32 the acc_fir_i input needs to be modified to 6 bit input.

**Comment by mkurc-ant** [comment]
@rakeshm75 I have updated width of `acc_fir_i` ports. Please check.

**Comment by rakeshm75** [comment]
@mkurc-ant, its good to merge now.

**Pull request merged**
